### ISSUE TITLE
Delete all branches before 1.6.0

### ISSUE THREAD

**Issue by lucasstarsz** [fastjengine/FastJ#130]
The repo needs a clean-up and re-structuring, as part of a bigger revamp of the engine's repo maintenance.

- [x] ~~merge `slf4j`~~ merged #127
- [x] ~~merge `1.6.0-display`~~ merged #124
- [x] ~~merge `version-system`~~ disregarded as moved from 1.6.0 to later release #123 
- [x] ~~merge `fix-packages`~~ merged #134 
- [x] delete old branches (`audio`, `examples`, etc)
- [x] handle dependabot (#144) branches
- [x] delete `physics` branch until a later time
